### ISSUE TITLE
Create new asset category "Assets"

### ISSUE THREAD

**Issue by mockersf** [bevyengine/bevy-assets#148]
I would like to create a new asset category called "Assets", and moving a few of those present in "Helper":
- [x] `bevy_asset_loader` by @NiklasEi 
- [x] `bevy_asset_ron` by @inodentry 
- [x] `bevy_assetio_zip` by katharostech (@zicklag ?)
- [x] `bevy_assets_bundler` by @hanabi1224 
- [x] `bevy_embedded_assets` by @mockersf 
-  ~~[ ]`bevy_loading`  by @inodentry~~
- [ ] `bevy_prototype_inline_assets` by @emosenkis 
- [x] `bevy_web_asset` by @johanhelsing 

Could you reply on this issue if you agree or if you can think of a better name? Thanks!

**Comment by inodentry** [comment]
I don't think my `bevy_loading` crate belongs in this category. It isn't really about assets.

It's a general-purpose state transition helper. Its goal is to let you track "progress" in an app state where you need to wait for the completion of a bunch of arbitrary things, and then transition to the next state when they are done. Typical uses are loading screens, splash screens, etc.

As a secondary feature, it offers tracking assets using this system, but I intend to make that optional.

**Comment by NiklasEi** [comment]
I am fine with splitting the "Helper" category and moving `bevy_asset_loader`.

Not sure about the name though, because the parent is already called "Assets". Could we rename the parent from "Assets" to "Plugins"? As far as I can see only the template is not a bevy plugin and that could move to a sub-category of "Learning".

**Comment by mockersf** [comment]
> Not sure about the name though, because the parent is already called "Assets". Could we rename the parent from "Assets" to "Plugins"? As far as I can see only the template is not a bevy plugin and the "Templates" category could move under "Learning".

Cart was quite attached to "Assets" as the general name.

Maybe this new category could be "Asset Loader"?

**Comment by NiklasEi** [comment]
> Cart was quite attached to "Assets" as the general name.

Was that not about the whole page being called "Bevy Assets"? That would still fit if the sub-categories are "Learning", "Plugins", and "Apps".

> Maybe this new category could be "Asset Loader"?

Then I would only expect plugins adding support for new asset file extensions with custom `AssetLoader`s. But that's only a subset of the asset-related plugins.

**Comment by zicklag** [comment]
>  bevy_assetio_zip by katharostech (@zicklag ?)

Wow, I forgot I even made that. :)

I'm fine if that's added to the list, if that's the question.

**Comment by johanhelsing** [comment]
I agree the current category, "Helper", is too broad and doesn't really say much. Not completely sure about the name "Assets", though... kind of makes it sound like it's actual assets, and not something that works on/with assets.

> > Maybe this new category could be "Asset Loader"?
>
> Then I would only expect plugins adding support for new asset file extensions with custom AssetLoaders. But that's only a subset of the asset-related plugins.

How about "Asset Loading"? Should make it a little bit broader?

Just my suggestions, I don't have a very strong opinion either way.

`bevy_web_asset` implements AssetLoader and adds support for https:// prefixes, so I'm fine with it being in either "Asset Loader" or "Asset Loading".

**Comment by NiklasEi** [comment]
If "Plugins" is out for the parent category, I would prefer "Asset Loading" over "Assets"/"Asset Loader" for the new sub-category :+1: 

I just randomly saw that [the current Bevy book actually calls the category "Plugins" at the moment](https://bevyengine.org/learn/book/next-steps/). Whatever we end up calling it, we should update the book to keep it consistent.

**Comment by hanabi1224** [comment]
I think it's good for `bevy_assets_bundler`, thx.
