### ISSUE TITLE
Provide recommended image dimensions

### ISSUE THREAD

**Issue by djeedai** [bevyengine/bevy-assets#188]
The current image space on the website is 83.7 x 128 px. Most images are way larger than that. On the other hand, the current website layout is not very good and could be improved, which could lead to displaying a larger preview image in the future (and hopefully better the largest allowed description text, which is currently cropped; see #159). I think it would be nice to set expectations and provide a recommended image dimension, the largest we think we will reasonably ever display in the future for any asset.

For the sake of discussion I'd propose something like 256 x 256 px, which is about 2x the current display so would allow crisp rendering on high DPI monitors, and is square so we can future proof it with respect to various current and future layouts of the website. We can consider larger sizes too, but being mindful some images are animated (GIF) so disk size will grow quickly.

**Comment by mockersf** [comment]
> but being mindful some images are animated (GIF) so disk size will grow quickly.

We should also suggest a limit in file size. The biggest gif is currently 4.0MB, with the whole repo at 17MB, and the page load at 16.7MB

**Comment by rparrett** [comment]
It seems like something like 400x225 might be about right now that we are displaying these with a constant aspect ratio.
