### ISSUE TITLE
All gifs are broken

### ISSUE THREAD

**Issue by NiklasEi** [bevyengine/bevy-assets#210]
![Screenshot 2022-05-14 at 17-33-26 Bevy - Assets](https://user-images.githubusercontent.com/12236672/168437698-0b548fc9-a50e-4982-b297-62f6f31ff885.png)
Currently, all assets using a gif as a preview look broken.

**Comment by NiklasEi** [comment]
Might be an issue with `generate-assets` in the website repo. The generated links contain one `/assets` too much.
I guess I should move the issue there?

**Comment by mockersf** [comment]
If only gifs are impacted I would look at https://github.com/bevyengine/bevy-website/pull/360

**Comment by NiklasEi** [comment]
I'll take a look at it

**Comment by rparrett** [comment]
No longer broken
