### ISSUE TITLE
Enable Git LFS on this repo

### ISSUE THREAD

**Issue by alice-i-cecile** [bevyengine/bevy-assets#263]
We're storing significant amounts of binary (image) data, and should probably be using a better solution than raw git.

Git LFS is by far the most simple to integrate, so probably works well here.

**Comment by mockersf** [comment]
Not sure this would improve things a lot...

Pretty much all usages of this repo need the asset files, and they don't evolve much.

**Comment by alice-i-cecile** [comment]
Hmm. We'd get a higher storage cap IIRC, which would help *delay* migration to a database.

That said, that's almost certainly going to be required eventually, so I think I agree it's not really worth the time.
