### ISSUE TITLE
Make bevy_github_ci_template more prominent 

### ISSUE THREAD

**Issue by rparrett** [bevyengine/bevy-assets#318]
We manually sort "Official Bevy Examples" in the learning section, so there is precedent for this.

In my opinion, we should sort this first, add an image, and adjust the title to "Official Github Template."

This issue is motivated by a user who was under the impression that `Bevy Shell` was the official template because it is coincidentally currently sorted first and has a nice graphic with the bevy logo. That user then went on to have various issues with native builds during Bevy Jam 3.

**Comment by cart** [comment]
I'm on board for this!
