### ISSUE TITLE
Add a new category - "Persistence"

### ISSUE THREAD

**Issue by idanarye** [bevyengine/bevy-assets#335]
Currently there is only one plugin in the assets page that deals with games that save stuff to the disk to be loaded later - [bevy_save](https://crates.io/crates/bevy_save) - and it's located under "Helpers". But I'm aware of several other plugin that deal with such things:

* https://crates.io/crates/moonshine-save
* https://crates.io/crates/bevy-settings
* https://crates.io/crates/bevy-persistent
* https://crates.io/crates/bevy_pkv

They are not exactly the same - some deal with saving/loading scenes, others with resources or manually picked data - but I still think a category like "Persistence" or "Saving/Loading" or something like that would describe them neatly, and this is something important enough in gamedev to justify a separate category.

BTW - do we need permission from the authors to add these crates to the list, or can we just add them?

**Comment by alice-i-cecile** [comment]
Agree with the new category!

I'm generally on board with adding crates without author permission, although if they ask not to be listed for whatever reason we'll of course respect that.

**Comment by idanarye** [comment]
Good point. @Zeenobit, @tecbeast42, @umut-sahin, @johanhelsing - if any of you don't want to be listed, write here and I'll remove your plugin from the PR (or make a new PR to remove it if it already got merged)

**Comment by tecbeast42** [comment]
Totally fine for me :+1:
