### ISSUE TITLE
Awesome Bevy 2.0

### ISSUE THREAD

**Issue by rparrett** [bevyengine/bevy-assets#70]
There has been a lot of discussion in the bevy discord around possible improvements to Awesome Bevy. Some of these cool things don't fit well into the "single markdown file maintained by one person" model.

Cart has a vision for what an "Awesome Bevy 2.0" would look like:

* `awesome-bevy` becomes a structured file format (something like json or yaml)
* [bevy-website](https://github.com/bevyengine/bevy-website) consumes this dataset and renders it in a searchable / discoverable way
* in the short short term, do this "statically" / without the need for databases, auth, or "entry creation widgets" on the website

And some other thoughts

> i think making awesome-bevy "fairer" is a bit of a priority
>
> right now order is arbitrary / comes from how bold contributors decide to be and how willing i am to change the order
> 
> it would be nice to be able to provide a curated section of high quality plugins (and content)
> / with vetted licenses

Here's some prior art that may be of interest:

https://github.com/discord/discord-open-source (the back-end, anyway)

Here's the discord conversation that inspired this issue: 

https://discord.com/channels/691052431525675048/692572690833473578/829793619132022814

**Comment by mockersf** [comment]
done! https://bevyengine.org/assets/

**Comment by cart** [comment]
Great work :heart:
